//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerDetail
    {
        public string TrainerDetailID { get; set; }
        public string Experience { get; set; }
        public string Companies { get; set; }
        public string SkillSet { get; set; }
        public string TeachingExperience { get; set; }
        public string Rewards { get; set; }
        public string TeachingReason { get; set; }
        public string TrainerId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
