//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    //public partial class ModelDesignContainer : DbContext
    //{
        //public ModelDesignContainer()
        //    : base("name=ModelDesignContainer")
        //{
        //}
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        //public virtual DbSet<Appointment> Appointments { get; set; }
        //public virtual DbSet<Attendance> Attendances { get; set; }
        //public virtual DbSet<Bid> Bids { get; set; }
        //public virtual DbSet<BookMark> BookMarks { get; set; }
        //public virtual DbSet<Chat> Chats { get; set; }
        //public virtual DbSet<CommonDetail> CommonDetails { get; set; }
        //public virtual DbSet<ContactUs> ContactUs { get; set; }
        //public virtual DbSet<Course> Courses { get; set; }
        //public virtual DbSet<Document> Documents { get; set; }
        //public virtual DbSet<Enrollment> Enrollments { get; set; }
        //public virtual DbSet<Feedback> Feedbacks { get; set; }
        //public virtual DbSet<PaymentMode> PaymentModes { get; set; }
        //public virtual DbSet<Rating> Ratings { get; set; }
        //public virtual DbSet<Role> Roles { get; set; }
        //public virtual DbSet<Session> Sessions { get; set; }
        //public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        //public virtual DbSet<Status> Status { get; set; }
        //public virtual DbSet<Subscription> Subscriptions { get; set; }
        //public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        //public virtual DbSet<Trainee> Trainees { get; set; }
        //public virtual DbSet<TrainerDetail> TrainerDetails { get; set; }
        //public virtual DbSet<Trainer> Trainers { get; set; }
        //public virtual DbSet<TrainingType> TrainingTypes { get; set; }
        //public virtual DbSet<User> Users { get; set; }
        //public virtual DbSet<UserClaim> UserClaims { get; set; }
        //public virtual DbSet<UserLogin> UserLogins { get; set; }
        //public virtual DbSet<ValidationPasscode> ValidationPasscodes { get; set; }
    //}
}
