//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public string SocialMediaId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string TrDetailId { get; set; }
    
        public virtual User User { get; set; }
    }
}
